const DEFAULT_VOCAB_BATCH_COUNT = 3;
const SEND_DAILY_SLACK_BTN_LABEL = 'Send Daily Dutch Vocab';

module.exports = {
    DEFAULT_VOCAB_BATCH_COUNT: DEFAULT_VOCAB_BATCH_COUNT,
    SEND_DAILY_SLACK_BTN_LABEL: SEND_DAILY_SLACK_BTN_LABEL
}