const DEFAULT_VOCAB_BATCH_COUNT = 3;
const SEND_DAILY_SLACK_BTN_LABEL = 'Send Daily Dutch Vocab';
const QUERY_EXECUTION_ERROR_MSG = 'Error executing query';
const QUERY_CONNECTION_ERROR_MSG = 'Error acquiring client';

module.exports = {
    DEFAULT_VOCAB_BATCH_COUNT: DEFAULT_VOCAB_BATCH_COUNT,
    SEND_DAILY_SLACK_BTN_LABEL: SEND_DAILY_SLACK_BTN_LABEL,
    QUERY_EXECUTION_ERROR_MSG: QUERY_EXECUTION_ERROR_MSG,
    QUERY_CONNECTION_ERROR_MSG: QUERY_CONNECTION_ERROR_MSG
}